version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: convert_files
    ports:
      - "8000:8000"
    entrypoint:
      - ./entrypoint.sh
    volumes:
      - ./config:/app/config
      - ./media:/app/media
      - ./src:/app/src
      - ./venv:/app/venv
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:////app/db.sqlite3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/certs:/etc/ssl/certs
