version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: convert_files
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./media:/app/media
      - ./src:/app/src
      - ./venv:/app/venv
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:////app/db.sqlite3
