# Generated by Django 4.2.2 on 2023-08-05 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('requests_remaining', models.IntegerField(default=250)),
            ],
            options={
                'verbose_name': 'Ключи',
                'verbose_name_plural': 'Ключи',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя файла')),
                ('file_path', models.FileField(upload_to='file/', verbose_name='Путь файла')),
                ('file_name', models.CharField(blank=True, max_length=50, verbose_name='Идентификатор файла')),
                ('previous_format', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий формат')),
                ('current_format', models.CharField(blank=True, max_length=20, verbose_name='Текущий формат')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
    ]
