# Generated by Django 4.2.2 on 2023-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='file/', verbose_name='Путь файла')),
                ('file_name', models.CharField(blank=True, max_length=20, verbose_name='Имя файла')),
                ('previous_format', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий формат')),
                ('current_format', models.CharField(blank=True, max_length=20, verbose_name='Текущий формат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступ')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
    ]
