# Generated by Django 4.2.2 on 2023-07-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('requests_remaining', models.IntegerField(default=250)),
            ],
        ),
    ]
