# Generated by Django 4.2.2 on 2023-08-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='file_path',
            new_name='file',
        ),
    ]
