# Generated by Django 4.2.2 on 2023-07-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'Ключи', 'verbose_name_plural': 'Ключи'},
        ),
    ]
