# Generated by Django 4.2.2 on 2023-07-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_alter_apikey_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='file_path',
            new_name='file',
        ),
    ]
